name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      matrix:
        target:
          - +test-python3.6
          - +test-python3.8-arrow0.x.x
          - +test-python3.8-arrow1.x.x
          - +test-python3.8-arrow2.x.x
          - +test-python3.8-arrow3.x.x
        experimental: [ false ]
        include:
          - target: +test-python3.8-arrow-nightly
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Earthly version
        run: earthly --version
      - name: Run build
        run: earthly --allow-privileged ${{ matrix.target }}
        continue-on-error: ${{ matrix.experimental }}