name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      matrix:
        target:
          - +test-python3.6
          - +test-python3.8-arrow0.x.x
          - +test-python3.8-arrow1.x.x
          - +test-python3.8-arrow2.x.x
        experimental: [ false ]
        upload: [ false ]
        include:
          - target: +test-python3.8-arrow3.x.x
            experimental: false
            upload: true
          - target: +test-python3.8-arrow-nightly
            experimental: true
            upload: false
    steps:
      - uses: actions/checkout@v2
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Earthly version
        run: earthly --version
      - name: Run build
        run: earthly --allow-privileged ${{ matrix.target }}
        continue-on-error: ${{ matrix.experimental }}

      # disable Python code coverage for now
      # as it is unclear why no coverage report file is created during the test
      # - name: Upload coverage for Python
      #   if: ${{ matrix.upload }} == 'true'
      #   uses: codecov/codecov-action@v1
      #   with:
      #     files: cov/python/coverage.xml
      #     fail_ci_if_error: true
      #     verbose: true
      #     functionalities: gcov
      - name: Upload coverage for C++
        if: ${{ matrix.upload }} == 'true'
        uses: codecov/codecov-action@v1
        with:
          directory: cov/cpp
          fail_ci_if_error: true
          verbose: true
          functionalities: coveragepy, gcov

      - name: Publish package
        if: ${{ matrix.upload }} == 'true' && env.IS_MASTER_BUILD == 'true' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'blue-yonder/turbodbc'

        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD }}